### ISSUE TITLE
ClassNotFoundException: net.wesjd.anvilgui.AnvilGui$Builder

### ISSUE THREAD

**Issue by Vampucha** [WesJD/AnvilGUI#131]
I cant find a solution for it, I tried several things from all the other issues now, nothing worked...

pom.xml
```
<build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.2.4</version>
                <configuration>
                    <minimizeJar>false</minimizeJar>
                    <artifactSet>
                        <includes>
                            <include>com.github.WesJD:AnvilGUI</include>
                        </includes>
                    </artifactSet>
                </configuration>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <repositories>
        <repository>
            <id>codemc-snapshots</id>
            <url>https://repo.codemc.io/repository/maven-snapshots/</url>
        </repository>
    </repositories>
    <dependencies>
        <dependency>
            <groupId>net.wesjd</groupId>
            <artifactId>anvilgui</artifactId>
            <version>1.4.0-SNAPSHOT</version>
            <scope>compile</scope>
        </dependency>
    </dependencies>
```

error: `java.lang.ClassNotFoundException: net.wesjd.anvilgui.AnvilGUI$Builder`

**Comment by portlek** [comment]
you don't have to add artifactSet configuration.

**Comment by Vampucha** [comment]
I tried a lot and I changed my pom.xml again, but it still does not work.
```
<repositories>
        <repository>
            <id>codemc-snapshots</id>
            <url>https://repo.codemc.io/repository/maven-snapshots/</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>net.wesjd</groupId>
            <artifactId>anvilgui</artifactId>
            <version>1.4.0-SNAPSHOT</version>
        </dependency>
    </dependencies>

    <build>
        <defaultGoal>clean package install</defaultGoal>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.2.3</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <minimizeJar>true</minimizeJar>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>
    </build>
```

**Comment by portlek** [comment]
what do you write to build your jar?

**Comment by Vampucha** [comment]
idk what you mean

**Comment by portlek** [comment]
what do write as a command to build your plugin file

**Comment by Vampucha** [comment]
I'm pressing the compile button in the Maven commands in Intellij

**Comment by portlek** [comment]
could you show the where you press it?

if it's
![image](https://user-images.githubusercontent.com/12835420/106453399-52b0ed00-649a-11eb-8a78-f8c6db800acb.png)
the green button, please show inside it.

**Comment by portlek** [comment]
![image](https://user-images.githubusercontent.com/12835420/106453528-82f88b80-649a-11eb-9aca-99c43f900be7.png)
![image](https://user-images.githubusercontent.com/12835420/106453551-8d1a8a00-649a-11eb-898a-c9ed7bb61c9e.png)

**Comment by Vampucha** [comment]
I recreated what youve shown me, now I'm getting again the error "unmappable character (0xA7) for encoding UTF-8"

**Comment by Vampucha** [comment]
and before I just pressed this compile button here
![image](https://user-images.githubusercontent.com/62899218/106453892-415fe480-648a-11eb-9ba7-33d3b92fb36e.png)

**Comment by portlek** [comment]
click the install or package button.

**Comment by Vampucha** [comment]
Ive tried everything and nothing worked for me. And I still have this error 
![image](https://user-images.githubusercontent.com/62899218/106454424-03af8b80-648b-11eb-912a-9a97ecad3273.png)

**Comment by portlek** [comment]
could you add this to your pom file?
```xml
<properties>
  <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  <java.version>1.8</java.version>
</properties>
````
and this plugin to build/plugins
```xml
<plugin>
  <groupId>org.apache.maven.plugins</groupId>
  <artifactId>maven-compiler-plugin</artifactId>
  <version>3.8.1</version>
  <configuration>
    <source>${java.version}</source>
    <target>${java.version}</target>
  </configuration>
</plugin>
```

**Comment by Vampucha** [comment]
still the same error
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>HomePlugin</artifactId>
    <version>1.0-SNAPSHOT</version>

    <repositories>
        <repository>
            <id>codemc-snapshots</id>
            <url>https://repo.codemc.io/repository/maven-snapshots/</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>net.wesjd</groupId>
            <artifactId>anvilgui</artifactId>
            <version>1.4.0-SNAPSHOT</version>
        </dependency>
    </dependencies>

    <build>
        <defaultGoal>clean package install</defaultGoal>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.2.3</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <minimizeJar>true</minimizeJar>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>
    </build>

    <properties>
        <maven.compiler.source>15</maven.compiler.source>
        <maven.compiler.target>15</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <java.version>1.8</java.version>
    </properties>
</project>
```
this is my entire pom.xml maybe i missed something

**Comment by portlek** [comment]
remove these
<maven.compiler.source>15</maven.compiler.source>
<maven.compiler.target>15</maven.compiler.target>
<defaultGoal>clean package install</defaultGoal>

**Comment by Vampucha** [comment]
Still the character error

**Comment by Vampucha** [comment]
I tried solutions from others posts but they didn't work for me

**Comment by portlek** [comment]
https://stackoverflow.com/a/8979120

**Comment by Vampucha** [comment]
still doenst work

**Comment by portlek** [comment]
is your project open-source or something like that? i want to try to build it. i couldn't find the problem :/

**Comment by Vampucha** [comment]
yea, I couldnt find it too, thats why i asked
my project isnt open source, should i upload it somewhere?

**Comment by portlek** [comment]
yea you can upload it to your GitHub page so I can see the problem easily.

**Comment by Vampucha** [comment]
alright

**Comment by Vampucha** [comment]
ok its uploaded https://github.com/Vampucha/HomePlugin

**Comment by portlek** [comment]
done, check your pull requests.

**Comment by Vampucha** [comment]
now i get this slight different error and the § still does not work, but there is no error on building anymore 
![image](https://user-images.githubusercontent.com/62899218/106478737-ce666600-64a9-11eb-9141-dd601ea77214.png)

**Comment by WesJD** [comment]
This repository is not a public chat for support. Please move this discussion elsewhere.
